### ISSUE TITLE
BATO.TO (revived) source is not getting downloaded and installed on the tachiyomi app

### ISSUE THREAD

**Issue by Debagnik** [ThePBone/tachiyomi-extensions-revived#2]
### Source information

BATO.TO

### Source language

English

### Steps to reproduce

1. Followed the steps on the readme.md to download and install mangadex
2. searched for bato.to on the source list and clicked on the download and install button
3. Button for download starts but immediately stops

### Expected behavior

Sources from the revived repo should install download and install

### Actual behavior

A Specific revived source (Bato.to) didn't get downloaded and installed

### Tachiyomi version

Preview r6396

### Android version

Android 12

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ThePBone** [comment]
Fixed. The download will work again.
