### ISSUE TITLE
Merge this project with another repo project

### ISSUE THREAD

**Issue by goliv04053** [ThePBone/tachiyomi-extensions-revived#21]
### Describe why this should be added

There is a project with similar goals like yours. It's from a user named keiyoushi. I think it would be interesting with both working togheter. 

### Other details

The github repo in question: https://github.com/keiyoushi/extensions-source

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by ThePBone** [comment]
I have added a link to the successor of Tachiyomi called [Mihon](https://reddit.com/r/mihonapp) as well as [keiyoushi/extensions](https://github.com/keiyoushi/extensions) 

I'll keep this repo open for archival purposes for now; there probably won't be any further updates in here.
