### ISSUE TITLE
Source request: nettruyen

### ISSUE THREAD

**Issue by HuyHoang01** [ThePBone/tachiyomi-extensions-revived#22]
### Source information

Source name: NetTruyen

### Source language

Vietnamese

### Source new URL

https://www.nettruyenclub.com/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by ThePBone** [comment]
Added by #29
