### ISSUE TITLE
URL change request for hayalistic

### ISSUE THREAD

**Issue by Metincloup** [ThePBone/tachiyomi-extensions-revived#25]
### Source information

Hayalistic 1.4.32

### Source language

Turkish 

### Source new URL

https://hayalistic.com.tr/

### Other details

Current Hayalistic url set to https://hayalistic.com and site has moved to https://hayalistic.com.tr url so couldn't connect Hayalistic.

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by ThePBone** [comment]
Fixed by #28
