### ISSUE TITLE
URL change request for Westmanga

### ISSUE THREAD

**Issue by thepurpleguy42673** [ThePBone/tachiyomi-extensions-revived#26]
### Source information

Westmanga 1.4.29

### Source language

Indonesian

### Source new URL

https://westmanga.fun

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by ThePBone** [comment]
Fixed by #26
