### ISSUE TITLE
Shinigami : URL Change Request

### ISSUE THREAD

**Issue by thepurpleguy42673** [ThePBone/tachiyomi-extensions-revived#34]
### Source information

Shinigami 1.4.41

### Source language

Indonesian

### Source new URL

https://shinigamitoon.com

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by ThePBone** [comment]
Fixed by #35
